env:
  commonjs: true
  es2021: true
  node: true
extends:
  - xo
  - plugin:prettier/recommended
globals:
  $: writable
  afterAll: writable
  alert: writable
  beforeAll: writable
  beforeEach: writable
  describe: writable
  document: writable
  expect: writable
  fetch: writable
  jest: writable
  it: writable
  parseInt: writable
parserOptions:
  ecmaVersion: latest
plugins:
  - prettier
rules: {
  prettier/prettier: warn
}

