env:
  commonjs: true
  es2021: true
  node: true
extends:
  - xo
  - plugin:prettier/recommended
globals:
  expect: writable
  it: writable  
parserOptions:
  ecmaVersion: latest
plugins:
  - prettier
rules: {
  prettier/prettier: warn
}

