printWidth: 90
tabWidth: 2
singleQuote: true
semi: true
trailingComma: all
# More space is better for readability
bracketSpacing: true
# Include parentheses around a sole arrow function parameter.
arrowParens: always